### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by gleachkr** [davidfaraci/margy#1]
An upload progress bar would be a nice addition for letter uploads.

**Comment by davidfaraci** [comment]
Took a look around. Seems like there are a few ways to do this. Will do some research on the lightest-weight one, or let me know if you have preferences.

**Comment by gleachkr** [comment]
No preference. The only way I could find to do it was along these lines:

http://stackoverflow.com/questions/15410265/file-upload-progress-bar-with-jquery

But that would require a little bit of rewriting of the POST route to handle JSON, along these lines:

http://stackoverflow.com/questions/14908864/how-can-i-use-data-posted-from-ajax-in-flask

**Comment by gleachkr** [comment]
Looks like this is pretty much addressed by ec6ab84e30b0146ed8845161afec0f09bfd33f45.
