### ISSUE TITLE
letter size

### ISSUE THREAD

**Issue by samanthamm** [davidfaraci/margy#2]
Hello, I would, first, like to express my gratitude for the development of this service.  Second, I just had a letter writer attempt to upload a letter to MARGY.  However, his file was rejected as too large.  He then removed the letterhead and it went through.  I was wondering if this was a common problem, or if there was anything that can be done about it.  

Thank you,
Samantha

p.s. I also sent this to the admin email, so please ignore the duplicate if need be

**Comment by davidfaraci** [comment]
Fixed. System should now accept PDFs up to 16 MB.
