### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by Ubu7538** [davidfaraci/margy#5]
Hello,

I tried to use the service, but the whitelist is incredibly restrictive.
I really like the project and the idea behind it, and I believe it has a lot of potential. However, as long as the whitelist is kept so short, I don't really see how it can be useful or aim to represent an alternative to services like interfolio: I simply cannot apply to any of the jobs (currently around 100) that I would want to apply to.
I suppose a solution would be to remove the whitelist altogether. At least at the present moment, given how little the service is used, I don't see a high risk of people using the service to send spam or the like (if this is the rationale behind it, and if I am right that the service isn't widely used yet).
Please do keep me posted if you find a solution to this!

Cheers

**Comment by davidfaraci** [comment]
The whitelist doesn’t exist to prevent spam; it exists to maintain
confidentiality. If there are jobs you want to apply to that are accepting
letters by email, all you need to do is show us evidence of such and we
will add the address to the whitelist.

**Comment by Ubu7538** [comment]
Hi, thanks for the quick reply! I understand now.
A quick, related note: I think other potential users might also (i) be put off by the short whitelist, and (ii) think twice before requesting additions to the whitelist – they might not want to bother you, or be worried about the time it may take for the list to be updated (applicants have to meet deadlines). 
This is just to suggest that (if you want to expand userbase) you might want to quickly address these worries on the website or on a FAQ page.
Anyway, thanks for launching this great project!
